### ISSUE TITLE
Cannot find module "async"

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-functions-pack#72]
We have been using funcpack successfully for many months, but recently it seems to be having issues with the async module which we rely on very heavily.  

Everything is running fine in the local Functions Emulator, the code is committed to VSO which is set up as a deployment source for the function app.  To fix this all we have to do is change the value of SCM_USE_FUNCPACK to 0 but then we see the execution time of our functions go way up.

This is the error from the console:
 
> 2018-02-23T03:09:44.826 [Error] Exception while executing function: Functions.Controller_Report. mscorlib: One or more errors occurred. Error: Cannot find module "async"
>     at webpackMissingModule (D:\home\site\wwwroot\.funcpack\index.js:193949:79)
>     at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:193949:161)
>     at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30)
>     at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:59046:28)
>     at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30)
>     at module.exports.SUGAR_GLOBAL (D:\home\site\wwwroot\.funcpack\index.js:64:18)
>     at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:67:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32).

**Comment by dr-jaah** [comment]
Hello graham, I'm finding the same error when i deploy my functions to Azure. Did you find any solution besides the one you mention?

**Comment by graham-sportsmgmt** [comment]
No solution at this point.  I believe the functions team is focused on the next version which might just solve this problem at the core.
