### ISSUE TITLE
funcpack on Mac with AFCT 2.0.1-beta.24 doesn't produce runnable function app.

### ISSUE THREAD

**Issue by bedej** [Azure/azure-functions-pack#77]
I have a node.js function which runs successfully and I can test with "func host start".

I then run "funcpack pack ./" per the README.md. When I run "func host start" again, I get the below error spew.

I suspect funcpack may not work with AFCT v2? Just a guess since the README instructions say to use "func run" which appears to be a deprecated command in v2.

Http Functions:

	GeneratePdf: http://localhost:7071/api/GeneratePdf

info: Worker.Node.26573904-abd1-47aa-9709-3ebc204ffbfd[0]
      Worker was unable to load function GeneratePdf: 'Error: ENOENT: no such file or directory, open '/Users/bedejordan/Workspace/shelf19/src/functions/MiscellaneousServices/.funcpack/classes.trie''
info: Worker.Node.26573904-abd1-47aa-9709-3ebc204ffbfd[0]
      Worker 26573904-abd1-47aa-9709-3ebc204ffbfd malformed message functionLoadResponse.result.result: string expected
info: Worker.Node.26573904-abd1-47aa-9709-3ebc204ffbfd[0]
      Worker 26573904-abd1-47aa-9709-3ebc204ffbfd uncaught exception:  functionLoadResponse.result.result: string expected
info: Worker.Node.26573904-abd1-47aa-9709-3ebc204ffbfd[0]
      Worker 26573904-abd1-47aa-9709-3ebc204ffbfd exited with code 1
fail: Worker.Node.26573904-abd1-47aa-9709-3ebc204ffbfd[0]
      Worker encountered an error.
info: Worker.Node.95a6dcda-491a-4c65-bdbe-ce946dcf91ac[0]
      Start Process: node  --inspect=5858 "/Users/bedejordan/.nvm/versions/node/v8.10.0/lib/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 61332 --workerId 95a6dcda-491a-4c65-bdbe-ce946dcf91ac --requestId 5acb41db-1f54-4470-bafc-ae1d82d74493

**Comment by bedej** [comment]
Actually the title isn't the reason - this doesn't work on Windows with AFCT v1 either. The same failure occurs after packing and running the functions locally, but only after a request comes in:

[3/17/18 9:27:06 PM] A ScriptHost error has occurred
[3/17/18 9:27:06 PM] Exception while executing function: Functions.GeneratePdf. mscorlib: One or more errors occurred. Error: ENOENT: no such file or directory, open 'C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\classes.trie'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:52495)
    at Object.<anonymous> (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:54189)
    at e (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:177)
    at Object.<anonymous> (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:12807)
    at e (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:177)
    at Object.<anonymous> (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:107838)
    at e (C:\github\shelf5\src\functions\MiscellaneousServices\.funcpack\index.js:1:177).

**Comment by ghost** [comment]
Any update on this? I bundled my function app with Webpack and I get the same error when calling it. 

> Exception while executing function: Functions.credit-app. mscorlib: One or more errors occurred. Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\classes.trie'
